apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::960603541212:role/EKSNodeGroup-NodeInstanceRole-1KCY31FYUM9W1	
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::960603541212:role/eks-cluster
      username: eks-cluster
      groups: 
        - system:masters


